"""baseline_v0_1

Revision ID: 21e83df6ddb0
Revises: 
Create Date: 2026-06-23 12:01:51.797704
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '21e83df6ddb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oidc_states',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oidc_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oidc_states_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oidc_states_state'), ['state'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'GUEST', name='userrole'), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_edit_metadata', sa.Boolean(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('oidc_subject', sa.String(length=255), nullable=True),
    sa.Column('oidc_issuer', sa.String(length=512), nullable=True),
    sa.Column('reader_theme', sa.String(length=16), nullable=False),
    sa.Column('reader_font_size', sa.Integer(), nullable=False),
    sa.Column('reader_line_height', sa.Float(), nullable=False),
    sa.Column('reader_font_family', sa.String(length=64), nullable=False),
    sa.Column('kindle_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_oidc_subject'), ['oidc_subject'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('highlights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('cfi', sa.String(length=512), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('chapter', sa.String(length=512), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_highlights_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_highlights_user_id'), ['user_id'], unique=False)

    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=512), nullable=False),
    sa.Column('position_type', sa.String(length=16), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('total_reading_time', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_book')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_last_read_at'), ['last_read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_progress_user_id'), ['user_id'], unique=False)

    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('adapter_name', sa.String(length=64), nullable=False),
    sa.Column('formats_json', sa.Text(), nullable=False),
    sa.Column('destinations_json', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SCRAPING', 'PACKAGING', 'DONE', 'FAILED', 'CANCELLED', name='scrapejobstatus'), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('total_bytes', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_paths_json', sa.Text(), nullable=True),
    sa.Column('imported_book_ids_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('shelves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('icon', sa.String(length=32), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('shelf_type', sa.Enum('MANUAL', 'READING', 'FINISHED', 'WISHLIST', 'FAVORITES', 'CUSTOM', name='shelftype'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'slug', name='uq_user_shelf_slug')
    )
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelves_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelves_user_id'), ['user_id'], unique=False)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('annotations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('highlight_id', sa.Integer(), nullable=True),
    sa.Column('cfi', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['highlight_id'], ['highlights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annotations_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_annotations_user_id'), ['user_id'], unique=False)

    op.create_table('shelf_books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shelf_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelf_id'], ['shelves.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shelf_id', 'book_id', name='uq_shelf_book')
    )
    with op.batch_alter_table('shelf_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shelf_books_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shelf_books_shelf_id'), ['shelf_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shelf_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelf_books_shelf_id'))
        batch_op.drop_index(batch_op.f('ix_shelf_books_book_id'))

    op.drop_table('shelf_books')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annotations_user_id'))
        batch_op.drop_index(batch_op.f('ix_annotations_book_id'))

    op.drop_table('annotations')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_expires_at'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('shelves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shelves_user_id'))
        batch_op.drop_index(batch_op.f('ix_shelves_slug'))

    op.drop_table('shelves')
    with op.batch_alter_table('scrape_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_scrape_jobs_status'))

    op.drop_table('scrape_jobs')
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_last_read_at'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_book_id'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_highlights_user_id'))
        batch_op.drop_index(batch_op.f('ix_highlights_book_id'))

    op.drop_table('highlights')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_oidc_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('oidc_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oidc_states_state'))
        batch_op.drop_index(batch_op.f('ix_oidc_states_created_at'))

    op.drop_table('oidc_states')
    # ### end Alembic commands ###
